---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - create
  - delete
  - get
  - list
  - watch
- apiGroups:
  - robotops.cloudhub.cz
  resources:
  - bootstraps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - robotops.cloudhub.cz
  resources:
  - bootstraps/finalizers
  verbs:
  - update
- apiGroups:
  - robotops.cloudhub.cz
  resources:
  - bootstraps/status
  verbs:
  - get
  - patch
  - update
